### PR TITLE
Justin django lab01

### PR DESCRIPTION
**Pull request by justin-young5**
optional part of lab not complete

### CODE REVIEW

**Comment by justin-young5** [comment]
the file I want to submit for lab is /Django/practice_lab/ and its contents ignore others please

**Review by violette-git — CHANGES_REQUESTED** [review]
Screenshot 2022-08-24 212322

The drop down doesn't have any values preventing me from submitting the form. Did you commit the right version?

**Comment by justin-young5** [comment]
lab should work as intended again please use the Django/practice_lab and its contents, ignore the others

**Comment by justin-young5** [comment]
worked on some optional items but the optional lab part is not complete while some of the elements are in the program

**Review by violette-git — APPROVED** [review]
Part 1 Blog Lab Complete. Great work.

**Pull request merged**
