### PR TITLE
Kacey lab03 number phrases

### PR DESCRIPTION
**Pull request by demolishen**

### CODE REVIEW

**Comment by demolishen** [comment]
lab02 fixes: class_HB2\code\kaceyb\python\lab02 lab_02.py
lab03 fixes: class_HB2\code\kaceyb\python\lab03 lab_03.py

**Comment by demolishen** [comment]
merge conflict resolved

**Comment by brucestull** [comment]
Lab 02 completed on https://github.com/PdxCodeGuild/class_HB2/pull/28.

**Review by brucestull — APPROVED** [review]
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases)

**Completed**

Great use of concantenation for result strings.

**Pull request merged**
