### PR TITLE
Created branch for lab 2 and fixed Git issue.

### PR DESCRIPTION
**Pull request by x8bitReignbeaux**

### CODE REVIEW

**Review by violette-git — CHANGES_REQUESTED** [review]
Since you included 2 labs in 1, and looks like you're going to add your portfolio as well. I can give you feedback for both here. They both look good. I like that you actually hooked up the navbar. For both the blog and company website lab, the footer is doing something interesting things. I suggest doing a little research to see if you can figure out what's happening. Make use of the _inspect element_ feature by right clicking on your webpage and also resize the page to see how your footer behaves. Other than that, your blog looks good. As for the Company website, try to build out that page a little more. Try to think of things a  company would include on their home page.  Use existing companies in the space as a reference.

**Comment by x8bitReignbeaux** [comment]
This is fixed in my lab 5 code (mostly). I can wrap it in another flex to fix the issue, but it happens at such a small resolution, it doesn't seem necessary right now. Will continue to work on it and will probably fix it once I learn enough to get the portfolio carousel working and polish the whole page up.

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 2: Blog](https://github.com/PdxCodeGuild/class_HB2/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/02%20Blog.md)

**Needs Work**

* Links and "Back to top" overlaps the blog posts. See attached image.

image

**Review by brucestull — APPROVED** [review]
**Completed**

* Great use of media queries `@media`.

**Pull request merged**
