### PR TITLE
Kelin lab03 number to phrases

### PR DESCRIPTION
**Pull request by rayk472**
Finished lab 3 version 1 and 2

### CODE REVIEW

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases)

**Needs Work**

Comments:
* Labs need to be submitted on their own branch. Please see me on how to break out Lab02 and Lab03 into their own branches.
* Your code has an inadvertent import of `truediv`. Sometimes imports happen automatically when we have typos and such. It's important to remove the un-needed imports before submitting code.
* Dictionary items should have single spaces after commas. See [PEP8 Style Guide](https://peps.python.org/pep-0008/#other-recommendations).

**Comment by rayk472** [comment]
Fixed the branch lab03 only on this branch. Removed accidental imports. Added spaces after commas in dictionaries. Thoroughly tested program. All numbers work between 0 and 999.

**Review by brucestull — CHANGES_REQUESTED** [review]
See me or Nathan.

Comments:
* Your Pull Request will delete some of your existing labs. We can check your commits and see if there is a way undo some commits.

**Review by brucestull — APPROVED** [review]
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases.md)

**Completed**

Comments:
* You've completed the lab but there are better ways to set up your dictionaries and logic. Take some time to consider how you could refactor the code.
* Please see me or one of the other TAs or the instructor to discuss how the code can be refactored to more effectively use dictionaries and conditional statements.

**Pull request merged**
