### PR TITLE
jonpan html lab02

### PR DESCRIPTION
**Pull request by notvert**

### CODE REVIEW

**Review by violette-git — CHANGES_REQUESTED** [review]
Consider moving your links into the navbar use bootstrap colors. There is also no information in your footer. I know you are going for minimum viable product. That would be minimum, add those and this will be complete.

**Review by brucestull — APPROVED** [review]
[Lab 2: Blog](https://github.com/PdxCodeGuild/class_HB2/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/02%20Blog.md)

**Completed**

Lab meets requirements. If you'd like to improve, find a way to use Flexbox to make the blog posts show side-by-side in wide view and then vertical column in narrow view.

**Review by brucestull — CHANGES_REQUESTED** [review]
See Grant's notes.

**Review by brucestull — APPROVED** [review]

**Comment by notvert** [comment]
Ask: 
- Consider moving your links into the navbar use bootstrap colors. 
- There is also no information in your footer. 

Changes:
- Added post links into topnav and used bootstrap color for topnav
- Added Placeholder

**Review by violette-git — APPROVED** [review]

**Pull request merged**
