### PR TITLE
Andy lab03 number phrases

### PR DESCRIPTION
**Pull request by andy2124**
this is the revised one.

### CODE REVIEW

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases)

**Needs Work**:

Comments:
* Program needs to provide a way for user to input their numbers to be converted to phrases.

**Review by brucestull — CHANGES_REQUESTED** [review]
Also, see me so we can break out the individual labs on their own branches. Labs should be on their own branch. See [Git Lab Workflow](https://github.com/PdxCodeGuild/class_HB2/blob/main/0%20General/11%20Git%20Lab%20Workflow.md).

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases)

**Needs Work**

Comments:
* Needs version 2 implemented.

**Review by brucestull — CHANGES_REQUESTED** [review]
**Needs Work**

Comments:
* Please use a filename for the python file which is representative of the lab number and lab name.
    * lab03_number_to_phrases.py
* Needs version 2 implemented.
* Please either have python file perform all versions sequentially or create separate python files for the required versions for this lab. See me if this comment isn't clear.

**Comment by nathanBonilla** [comment]
Great job Andy!  You used a very creative way to use list comprehension!  I'm very impressed.

There's just a couple things we need to change:
 - When I enter _100, 200, 300_... etc. it outputs: _one hundred zero, two hundred zero, three hundred zero_, and so on.
 - 999 returns none

On one very small side note, I noticed that in your dictionaries, you're alternating between apostrophes and quotation marks.  Try to stick to one or the other for consistency.  I personally use apostrophes for single words, and quotation marks for multiple words.  i.e. 'variable', "this is a sentence".

**Review by nathanBonilla — CHANGES_REQUESTED** [review]
There's just a couple things we need to change:

When I enter 100, 200, 300... etc. it outputs: one hundred zero, two hundred zero, three hundred zero, and so on.
999 returns none

On one very small side note, I noticed that in your dictionaries, you're alternating between apostrophes and quotation marks. Try to stick to one or the other for consistency. I personally use apostrophes for single words, and quotation marks for multiple words. i.e. 'variable', "this is a sentence".

**Review by nathanBonilla — CHANGES_REQUESTED** [review]
HI Andy, you haven't fixed the issues that I mentioned above.

If I enter 100,
"one hundred zero" is outputted

If I enter 999,
"None" is outputted

**Review by nathanBonilla — APPROVED** [review]
Awesome job Andy!

**Pull request merged**
